(() => {
  'use strict';

  const KEYS = { profile: 'pathly.profile.v1', prefs: 'pathly.preferences.v1' };
  const app = document.querySelector('#app');
  const toast = document.querySelector('#toast');
  let photoObjectUrl = '';

  const COPY = {
    en: {
      tagline: 'Your Path. Your Profile. Your Future.', dashboard: 'Dashboard', profile: 'Profile', cv: 'CV', portfolio: 'Portfolio', advisor: 'Career Advisor',
      buildProfile: 'Build My Profile', explore: 'Explore Pathly', getStarted: 'Get Started', loadExample: 'Load example', startBlank: 'Start blank profile', clearData: 'Clear local data',
      landingHeadline: 'Build Your Profile. Shape Your Future.', description: 'Pathly helps you build a professional profile, create your CV and portfolio, and discover the next steps in your career journey.',
      featureProfile: 'Build Your Profile', featureProfileText: 'Add your story once and keep every career document in sync.', featureCv: 'Create Your CV', featureCvText: 'Turn your profile into a concise, print-ready CV.', featurePath: 'Discover Your Path', featurePathText: 'Get practical next steps based only on your saved profile.',
      journey: 'Your Journey with Pathly', journeyFlow: 'Profile → CV & Portfolio → Career Guidance', aboutCreator: 'About the Creator', aboutText: "Hi, I'm Ahmed, the creator of Pathly. I created Pathly to help students and professionals build a stronger professional profile, discover their career path, and take practical steps toward their future.",
      ready: 'Ready to build your future?', nextStep: 'Your next step', privacy: 'Your information stays in this browser. Pathly does not create accounts or send your details anywhere.',
      welcome: 'Welcome back', profileStrength: 'Profile Strength', careerGoal: 'Career Goal', skillsProgress: 'Skills Progress', quickActions: 'Quick actions', viewCV: 'View CV', viewPortfolio: 'View Portfolio', getGuidance: 'Get guidance', completeProfile: 'Complete your profile to unlock a stronger picture of your path.',
      basics: 'Your basics', photo: 'Profile photo (optional)', changePhoto: 'Choose photo', removePhoto: 'Remove photo', fullName: 'Full Name', email: 'Email', about: 'About Me', contactLinks: 'Contact & links', linkedin: 'LinkedIn', github: 'GitHub',
      education: 'Education', university: 'University', major: 'Major / Specialization', degree: 'Degree', experience: 'Work Experience', role: 'Role', company: 'Organization', start: 'Start', end: 'End', descriptionLabel: 'Description',
      skills: 'Skills', addSkill: 'Add a skill', projects: 'Projects', projectName: 'Project name', tools: 'Tools / technologies', link: 'Project link', certifications: 'Certifications', certification: 'Certification', issuer: 'Issuer', date: 'Date', languages: 'Languages', addLanguage: 'Add a language',
      addEducation: 'Add education', addExperience: 'Add experience', addProject: 'Add project', addCertification: 'Add certification', remove: 'Remove', saveLocal: 'Saved locally', profileUpdated: 'Your profile has been updated locally.',
      cvTitle: 'Create a CV from your profile', cvSubtitle: 'Choose a template. Empty sections stay out of your document.', printPdf: 'Print / Save as PDF', printHelp: 'Choose “Save as PDF” in your browser print dialog.', template: 'Template', modern: 'Modern', classic: 'Classic', focused: 'Focused',
      portfolioTitle: 'Create a portfolio from the same story', portfolioSubtitle: 'Choose a responsive look for your work.', minimal: 'Minimal', creative: 'Creative', professional: 'Professional', downloadPortfolio: 'Download portfolio HTML', shareOnline: 'Share online', shareInfo: 'Your portfolio is private in this browser. Download the HTML first, then host that file wherever you choose.',
      advisorTitle: 'Personalized career guidance', advisorSubtitle: 'Clear, local guidance based only on what you entered.', strengths: 'Profile strengths', gaps: 'Skills to improve', directions: 'Suggested directions', courses: 'Recommended courses', projectIdeas: 'Practical project ideas', improvements: 'CV & profile improvements', journeyTitle: 'Your next-step journey', ruleNote: 'These recommendations are generated locally from your profile and fixed career rules — not an AI service.',
      currentProfile: 'Current Profile', targetCareer: 'Target Career', missing: 'Not added yet', empty: 'Nothing here yet', addFirst: 'Add your first item', confirmReplace: 'Replace your current profile with the fictional example?', confirmClear: 'Clear all Pathly data from this browser?', yes: 'Yes, continue', cancel: 'Cancel', language: 'العربية', theme: 'Dark mode', themeLight: 'Light mode', exampleLoaded: 'Fictional example loaded locally.', blankStarted: 'Started with a blank profile.', cleared: 'Local profile data cleared.', photoTooLarge: 'That photo could not be saved. Try a smaller image.', storageIssue: 'Your browser could not save this change locally.',
      tips: ['Add an About Me summary', 'Include education or experience', 'List skills that support your goal', 'Show a project that demonstrates your work'],
      roleFallback: 'Choose a clear target role and add skills or projects to receive more focused guidance.', goalPlaceholder: 'For example: Frontend Developer'
    },
    ar: {
      tagline: 'مسارك. ملفك. مستقبلك.', dashboard: 'لوحة التحكم', profile: 'الملف الشخصي', cv: 'السيرة الذاتية', portfolio: 'ملف الأعمال', advisor: 'مستشار المسار',
      buildProfile: 'أنشئ ملفي', explore: 'استكشف باثلي', getStarted: 'ابدأ الآن', loadExample: 'تحميل مثال', startBlank: 'ابدأ ملفاً فارغاً', clearData: 'مسح البيانات المحلية',
      landingHeadline: 'ابنِ ملفك. شكّل مستقبلك.', description: 'يساعدك باثلي على إنشاء ملف مهني، وإعداد سيرتك الذاتية وملف أعمالك، واكتشاف الخطوات التالية في رحلتك المهنية.',
      featureProfile: 'ابنِ ملفك الشخصي', featureProfileText: 'أضف قصتك مرة واحدة وحافظ على تزامن كل مستنداتك المهنية.', featureCv: 'أنشئ سيرتك الذاتية', featureCvText: 'حوّل ملفك إلى سيرة ذاتية موجزة وجاهزة للطباعة.', featurePath: 'اكتشف مسارك', featurePathText: 'احصل على خطوات عملية مبنية فقط على ملفك المحفوظ.',
      journey: 'رحلتك مع باثلي', journeyFlow: 'الملف الشخصي ← السيرة وملف الأعمال ← الإرشاد المهني', aboutCreator: 'عن المؤسس', aboutText: 'مرحباً، أنا أحمد، منشئ باثلي. أنشأت باثلي لمساعدة الطلاب والمهنيين على بناء ملف مهني أقوى، واكتشاف مسارهم المهني، واتخاذ خطوات عملية نحو مستقبلهم.',
      ready: 'هل أنت مستعد لبناء مستقبلك؟', nextStep: 'خطوتك التالية', privacy: 'تبقى معلوماتك في هذا المتصفح. لا ينشئ باثلي حسابات ولا يرسل بياناتك إلى أي مكان.',
      welcome: 'مرحباً بعودتك', profileStrength: 'قوة الملف الشخصي', careerGoal: 'الهدف المهني', skillsProgress: 'تقدم المهارات', quickActions: 'إجراءات سريعة', viewCV: 'عرض السيرة', viewPortfolio: 'عرض ملف الأعمال', getGuidance: 'احصل على إرشاد', completeProfile: 'أكمل ملفك لتكوين صورة أقوى لمسارك.',
      basics: 'بياناتك الأساسية', photo: 'صورة الملف (اختيارية)', changePhoto: 'اختر صورة', removePhoto: 'إزالة الصورة', fullName: 'الاسم الكامل', email: 'البريد الإلكتروني', about: 'نبذة عني', contactLinks: 'التواصل والروابط', linkedin: 'لينكدإن', github: 'جيت هب',
      education: 'التعليم', university: 'الجامعة', major: 'التخصص', degree: 'الدرجة', experience: 'الخبرة العملية', role: 'المسمى الوظيفي', company: 'الجهة', start: 'البداية', end: 'النهاية', descriptionLabel: 'الوصف',
      skills: 'المهارات', addSkill: 'أضف مهارة', projects: 'المشاريع', projectName: 'اسم المشروع', tools: 'الأدوات / التقنيات', link: 'رابط المشروع', certifications: 'الشهادات', certification: 'الشهادة', issuer: 'الجهة المانحة', date: 'التاريخ', languages: 'اللغات', addLanguage: 'أضف لغة',
      addEducation: 'أضف تعليماً', addExperience: 'أضف خبرة', addProject: 'أضف مشروعاً', addCertification: 'أضف شهادة', remove: 'إزالة', saveLocal: 'تم الحفظ محلياً', profileUpdated: 'تم تحديث ملفك محلياً.',
      cvTitle: 'أنشئ سيرة ذاتية من ملفك', cvSubtitle: 'اختر قالباً. الأقسام الفارغة لن تظهر في المستند.', printPdf: 'اطبع / احفظ PDF', printHelp: 'اختر «حفظ بتنسيق PDF» في نافذة الطباعة بالمتصفح.', template: 'القالب', modern: 'حديث', classic: 'كلاسيكي', focused: 'مركّز',
      portfolioTitle: 'أنشئ ملف أعمال من القصة نفسها', portfolioSubtitle: 'اختر مظهراً متجاوباً لأعمالك.', minimal: 'بسيط', creative: 'إبداعي', professional: 'احترافي', downloadPortfolio: 'تنزيل ملف الأعمال HTML', shareOnline: 'مشاركة عبر الإنترنت', shareInfo: 'ملف أعمالك خاص في هذا المتصفح. نزّل ملف HTML أولاً، ثم استضفه في المكان الذي تختاره.',
      advisorTitle: 'إرشاد مهني مخصص', advisorSubtitle: 'إرشاد محلي واضح مبني فقط على ما أدخلته.', strengths: 'نقاط قوة الملف', gaps: 'مهارات تحتاج إلى تطوير', directions: 'اتجاهات مقترحة', courses: 'دورات مقترحة', projectIdeas: 'أفكار مشاريع عملية', improvements: 'تحسينات السيرة والملف', journeyTitle: 'رحلة خطوتك التالية', ruleNote: 'تُنشأ هذه التوصيات محلياً من ملفك وقواعد مهنية ثابتة، وليست خدمة ذكاء اصطناعي.',
      currentProfile: 'الملف الحالي', targetCareer: 'المسار المستهدف', missing: 'لم يُضف بعد', empty: 'لا يوجد شيء هنا بعد', addFirst: 'أضف أول عنصر', confirmReplace: 'هل تريد استبدال ملفك الحالي بالمثال الخيالي؟', confirmClear: 'هل تريد مسح جميع بيانات باثلي من هذا المتصفح؟', yes: 'نعم، تابع', cancel: 'إلغاء', language: 'English', theme: 'الوضع الداكن', themeLight: 'الوضع الفاتح', exampleLoaded: 'تم تحميل المثال الخيالي محلياً.', blankStarted: 'بدأت بملف فارغ.', cleared: 'تم مسح بيانات الملف المحلية.', photoTooLarge: 'تعذر حفظ هذه الصورة. جرّب صورة أصغر.', storageIssue: 'تعذر على متصفحك حفظ هذا التغيير محلياً.',
      tips: ['أضف نبذة عنك', 'أضف تعليماً أو خبرة', 'أدرج مهارات تدعم هدفك', 'أظهر مشروعاً يثبت عملك'],
      roleFallback: 'اختر مسمى وظيفياً واضحاً وأضف مهارات أو مشاريع للحصول على إرشاد أكثر تركيزاً.', goalPlaceholder: 'مثال: مطور واجهات أمامية'
    }
  };

  const roles = {
    'frontend developer': { label: { en: 'Frontend Developer', ar: 'مطور واجهات أمامية' }, skills: ['html', 'css', 'javascript', 'git', 'responsive design'], courses: ['Modern HTML & CSS', 'JavaScript fundamentals', 'Accessible interface design'], projects: ['Build an accessible personal site', 'Create a responsive dashboard interface'] },
    'ux ui designer': { label: { en: 'UX/UI Designer', ar: 'مصمم تجربة وواجهة مستخدم' }, skills: ['user research', 'wireframing', 'prototyping', 'figma', 'accessibility'], courses: ['User-centred design', 'Interface prototyping', 'Accessibility essentials'], projects: ['Redesign a daily task flow', 'Document a small usability study'] },
    'data analyst': { label: { en: 'Data Analyst', ar: 'محلل بيانات' }, skills: ['spreadsheets', 'sql', 'statistics', 'data visualization', 'python'], courses: ['Spreadsheet analysis', 'SQL foundations', 'Data storytelling'], projects: ['Analyze a fictional survey dataset', 'Create a clear insight report'] },
    'project coordinator': { label: { en: 'Project Coordinator', ar: 'منسق مشاريع' }, skills: ['communication', 'planning', 'documentation', 'teamwork', 'project management'], courses: ['Project planning basics', 'Professional communication', 'Agile foundations'], projects: ['Create a project brief and timeline', 'Build a delivery-risk checklist'] }
  };

  const blankProfile = () => ({ fullName: '', photo: '', about: '', email: '', linkedin: '', github: '', careerGoal: '', education: [], experience: [], skills: [], projects: [], certifications: [], languages: [], cvTemplate: 'modern', portfolioTemplate: 'modern' });
  const defaults = { language: 'en', theme: 'light', view: 'landing' };
  let profile = load(KEYS.profile, null);
  let profileSeeded = false;
  if (!profile || typeof profile !== 'object') { profile = window.PathlyExampleData?.create?.() || blankProfile(); profileSeeded = true; }
  profile = { ...blankProfile(), ...profile };
  let prefs = { ...defaults, ...load(KEYS.prefs, {}) };

  function load(key, fallback) { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : fallback; } catch { return fallback; } }
  function save() { try { localStorage.setItem(KEYS.profile, JSON.stringify(profile)); localStorage.setItem(KEYS.prefs, JSON.stringify(prefs)); notify(t('profileUpdated')); } catch { notify(t('storageIssue')); } }
  function t(key) { return COPY[prefs.language][key] ?? key; }
  function esc(value = '') { const div = document.createElement('div'); div.textContent = String(value); return div.innerHTML; }
  function validUrl(value) { try { const url = new URL(value); return /^https?:$/.test(url.protocol); } catch { return false; } }
  function notify(message) { toast.textContent = message; toast.classList.add('is-visible'); clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.classList.remove('is-visible'), 3200); }
  function formatDate(value) { if (!value) return ''; const [year, month] = value.split('-'); if (!year || !month) return value; return new Intl.DateTimeFormat(prefs.language === 'ar' ? 'ar' : 'en', { month: 'short', year: 'numeric' }).format(new Date(Number(year), Number(month) - 1, 1)); }
  function dateRange(item) { const start = formatDate(item.start); const end = item.end ? formatDate(item.end) : (prefs.language === 'ar' ? 'الآن' : 'Present'); return [start, end].filter(Boolean).join(' — '); }

  function applyDocumentSettings() { document.documentElement.lang = prefs.language; document.documentElement.dir = prefs.language === 'ar' ? 'rtl' : 'ltr'; document.documentElement.dataset.theme = prefs.theme; document.title = `Pathly — ${t('tagline')}`; }
  function navItem(view, label) { return `<button class="nav-item ${prefs.view === view ? 'is-active' : ''}" data-view="${view}" type="button">${label}</button>`; }
  function toggleButton() { return `<div class="toolbar"><button class="utility-button" data-action="language" type="button" aria-label="${t('language')}">${t('language')}</button><button class="utility-button" data-action="theme" type="button" aria-label="${prefs.theme === 'light' ? t('theme') : t('themeLight')}">${prefs.theme === 'light' ? '◐' : '◑'} <span>${prefs.theme === 'light' ? t('theme') : t('themeLight')}</span></button></div>`; }
  function header() { return `<header class="topbar"><button class="brand" data-view="landing" type="button"><span class="brand-mark">P</span><span><strong>Pathly</strong><small>${t('tagline')}</small></span></button><nav class="primary-nav" aria-label="Pathly">${navItem('dashboard', t('dashboard'))}${navItem('profile', t('profile'))}${navItem('cv', t('cv'))}${navItem('portfolio', t('portfolio'))}${navItem('advisor', t('advisor'))}</nav>${toggleButton()}</header>`; }

  function landing() { return `<main id="main-content" class="landing">
    <div class="landing-top section-shell"><button class="brand" data-view="landing" type="button"><span class="brand-mark">P</span><span><strong>Pathly</strong><small>${t('tagline')}</small></span></button><div class="landing-controls">${toggleButton()}<button class="button button-quiet" data-action="example" type="button">${t('loadExample')}</button></div></div>
    <section class="hero section-shell"><div class="eyebrow">Pathly</div><h1>${t('landingHeadline')}</h1><p class="hero-copy">${t('description')}</p><div class="button-row"><button class="button button-primary" data-view="profile" type="button">${t('buildProfile')}</button><button class="button button-secondary" data-view="dashboard" type="button">${t('explore')}</button></div><p class="privacy-note">${t('privacy')}</p></section>
    <section class="section-shell"><div class="section-heading"><div><div class="eyebrow">01</div><h2>${t('journey')}</h2></div><p>${t('journeyFlow')}</p></div><div class="feature-grid">${featureCard('01', t('featureProfile'), t('featureProfileText'))}${featureCard('02', t('featureCv'), t('featureCvText'))}${featureCard('03', t('featurePath'), t('featurePathText'))}</div></section>
    <section class="section-shell about-card"><div class="eyebrow">Pathly</div><h2>${t('aboutCreator')}</h2><p>${t('aboutText')}</p></section>
    <section class="section-shell final-cta"><div><div class="eyebrow">${t('nextStep')}</div><h2>${t('ready')}</h2></div><button class="button button-primary" data-view="profile" type="button">${t('getStarted')}</button></section>
  </main>`; }
  function featureCard(number, title, text) { return `<article class="feature-card"><span>${number}</span><h3>${title}</h3><p>${text}</p></article>`; }

  function strength() { const checks = [profile.fullName, profile.about, profile.email, profile.education.length, profile.experience.length, profile.skills.length >= 2, profile.projects.length, profile.careerGoal]; return Math.round((checks.filter(Boolean).length / checks.length) * 100); }
  function dashboard() { const pct = strength(); const remaining = COPY[prefs.language].tips.filter((_, index) => ![profile.about, profile.education.length || profile.experience.length, profile.skills.length, profile.projects.length][index]); return `<main id="main-content" class="app-main section-shell">
    <div class="view-heading"><div><div class="eyebrow">Pathly / ${t('dashboard')}</div><h1>${t('welcome')}${profile.fullName ? `, ${esc(profile.fullName.split(' ')[0])}` : ''}.</h1><p>${t('completeProfile')}</p></div><button class="button button-quiet" data-action="example" type="button">${t('loadExample')}</button></div>
    <div class="dashboard-grid"><article class="metric-card strength-card"><div class="metric-label">${t('profileStrength')}</div><div class="strength-line"><strong>${pct}%</strong><progress max="100" value="${pct}">${pct}%</progress></div><p>${pct < 70 ? remaining.slice(0, 2).join(' · ') : t('profileUpdated')}</p></article><article class="metric-card"><div class="metric-label">${t('careerGoal')}</div><form data-form="goal" class="inline-goal"><input name="careerGoal" value="${esc(profile.careerGoal)}" placeholder="${t('goalPlaceholder')}" aria-label="${t('careerGoal')}"><button class="button button-small" type="submit">${t('saveLocal')}</button></form></article><article class="metric-card"><div class="metric-label">${t('skillsProgress')}</div><strong class="stat-number">${profile.skills.length}</strong><p>${profile.skills.length ? esc(profile.skills.join(' · ')) : t('missing')}</p></article></div>
    <section class="quick-section"><div class="section-heading compact"><div><div class="eyebrow">Next</div><h2>${t('quickActions')}</h2></div></div><div class="quick-grid"><button class="quick-action" data-view="cv" type="button"><span>01</span>${t('viewCV')}</button><button class="quick-action" data-view="portfolio" type="button"><span>02</span>${t('viewPortfolio')}</button><button class="quick-action" data-view="advisor" type="button"><span>03</span>${t('getGuidance')}</button></div></section>
  </main>`; }

  function field(label, name, value, type = 'text', placeholder = '') { return `<label class="field"><span>${label}</span><input type="${type}" name="${name}" value="${esc(value || '')}" placeholder="${placeholder}" autocomplete="off"></label>`; }
  function textField(label, name, value, placeholder = '') { return `<label class="field field-full"><span>${label}</span><textarea name="${name}" rows="4" placeholder="${placeholder}">${esc(value || '')}</textarea></label>`; }
  function repeatGroup(kind, title, fields, items) { return `<section class="form-group"><div class="form-heading"><h2>${title}</h2><button class="text-button" type="button" data-add="${kind}">${t(`add${kind[0].toUpperCase() + kind.slice(1)}`)}</button></div><div class="repeat-list">${items.length ? items.map((item, index) => `<article class="repeat-card" data-repeat="${kind}" data-index="${index}">${fields.map(f => f.type === 'textarea' ? textField(t(f.label), f.name, item[f.name], f.placeholder || '') : field(t(f.label), f.name, item[f.name], f.type || 'text', f.placeholder || '')).join('')}<button class="remove-button" type="button" data-remove="${kind}" data-index="${index}">${t('remove')}</button></article>`).join('') : `<p class="empty-inline">${t('empty')} — ${t('addFirst')}.</p>`}</div></section>`; }
  function tags(kind, label, values, addLabel) { return `<section class="form-group"><div class="form-heading"><h2>${label}</h2></div><div class="tag-list">${values.map((value, index) => `<span class="tag">${esc(value)}<button type="button" aria-label="${t('remove')} ${esc(value)}" data-remove-tag="${kind}" data-index="${index}">×</button></span>`).join('')}</div><form class="tag-form" data-tag-form="${kind}"><input name="value" placeholder="${addLabel}" aria-label="${addLabel}"><button class="button button-small" type="submit">${addLabel}</button></form></section>`; }
  function photoPreview() { if (!profile.photo) return ''; return `<img class="profile-photo" src="${profile.photo}" alt="${t('photo')}">`; }
  function profileView() { return `<main id="main-content" class="app-main section-shell"><div class="view-heading"><div><div class="eyebrow">Pathly / ${t('profile')}</div><h1>${t('buildProfile')}</h1><p>${t('privacy')}</p></div><div class="profile-actions"><button class="button button-quiet" data-action="blank" type="button">${t('startBlank')}</button><button class="button button-danger" data-action="clear" type="button">${t('clearData')}</button></div></div>
    <form id="profile-form" class="profile-form"><section class="form-group"><div class="form-heading"><h2>${t('basics')}</h2>${photoPreview()}</div><div class="form-grid">${field(t('fullName'), 'fullName', profile.fullName, 'text')}${field(t('email'), 'email', profile.email, 'email')}${textField(t('about'), 'about', profile.about)}</div><div class="photo-row"><label class="file-button"><input id="photo-input" type="file" accept="image/*">${t('changePhoto')}</label>${profile.photo ? `<button class="text-button" data-action="remove-photo" type="button">${t('removePhoto')}</button>` : ''}</div></section>
      <section class="form-group"><div class="form-heading"><h2>${t('contactLinks')}</h2></div><div class="form-grid">${field(t('linkedin'), 'linkedin', profile.linkedin, 'url', 'https://')}${field(t('github'), 'github', profile.github, 'url', 'https://')}</div></section>
      ${repeatGroup('education', t('education'), [{ label: 'university', name: 'university' }, { label: 'major', name: 'major' }, { label: 'degree', name: 'degree' }, { label: 'start', name: 'start', type: 'month' }, { label: 'end', name: 'end', type: 'month' }, { label: 'descriptionLabel', name: 'description', type: 'textarea' }], profile.education)}
      ${repeatGroup('experience', t('experience'), [{ label: 'role', name: 'role' }, { label: 'company', name: 'company' }, { label: 'start', name: 'start', type: 'month' }, { label: 'end', name: 'end', type: 'month' }, { label: 'descriptionLabel', name: 'description', type: 'textarea' }], profile.experience)}
      ${tags('skills', t('skills'), profile.skills, t('addSkill'))}
      ${repeatGroup('projects', t('projects'), [{ label: 'projectName', name: 'name' }, { label: 'tools', name: 'tools' }, { label: 'link', name: 'link', type: 'url', placeholder: 'https://' }, { label: 'descriptionLabel', name: 'description', type: 'textarea' }], profile.projects)}
      ${repeatGroup('certifications', t('certifications'), [{ label: 'certification', name: 'name' }, { label: 'issuer', name: 'issuer' }, { label: 'date', name: 'date', type: 'month' }, { label: 'link', name: 'link', type: 'url', placeholder: 'https://' }], profile.certifications)}
      ${tags('languages', t('languages'), profile.languages, t('addLanguage'))}
      <section class="form-group"><div class="form-heading"><h2>${t('careerGoal')}</h2></div><div class="form-grid">${field(t('careerGoal'), 'careerGoal', profile.careerGoal, 'text', t('goalPlaceholder'))}</div></section>
    </form></main>`; }

  function documentSections(kind = 'cv') { const links = [profile.email, profile.linkedin, profile.github].filter(Boolean); const blocks = [];
    if (profile.about) blocks.push(docSection(t('about'), `<p>${esc(profile.about)}</p>`));
    if (profile.experience.length) blocks.push(docSection(t('experience'), profile.experience.map(x => `<article class="doc-entry"><div><h4>${esc(x.role || '')}${x.company ? ` · ${esc(x.company)}` : ''}</h4><small>${dateRange(x)}</small></div>${x.description ? `<p>${esc(x.description)}</p>` : ''}</article>`).join('')));
    if (profile.education.length) blocks.push(docSection(t('education'), profile.education.map(x => `<article class="doc-entry"><div><h4>${esc([x.degree, x.major].filter(Boolean).join(' · '))}</h4><small>${esc(x.university || '')}${dateRange(x) ? ` · ${dateRange(x)}` : ''}</small></div>${x.description ? `<p>${esc(x.description)}</p>` : ''}</article>`).join('')));
    if (profile.projects.length) blocks.push(docSection(t('projects'), profile.projects.map(x => `<article class="doc-entry"><h4>${esc(x.name || '')}</h4>${x.tools ? `<small>${esc(x.tools)}</small>` : ''}${x.description ? `<p>${esc(x.description)}</p>` : ''}</article>`).join('')));
    if (profile.skills.length) blocks.push(docSection(t('skills'), `<p class="inline-list">${profile.skills.map(esc).join(' · ')}</p>`));
    if (profile.certifications.length) blocks.push(docSection(t('certifications'), profile.certifications.map(x => `<p>${esc([x.name, x.issuer, formatDate(x.date)].filter(Boolean).join(' · '))}</p>`).join('')));
    if (profile.languages.length) blocks.push(docSection(t('languages'), `<p class="inline-list">${profile.languages.map(esc).join(' · ')}</p>`));
    return `<div class="document-body"><header class="document-header">${profile.photo && kind === 'portfolio' ? `<img src="${profile.photo}" alt="">` : ''}<div><div class="doc-brand">Pathly</div><h2>${esc(profile.fullName || 'Your Name')}</h2>${profile.careerGoal ? `<p>${esc(profile.careerGoal)}</p>` : ''}${links.length ? `<div class="document-links">${links.map(esc).join(' · ')}</div>` : ''}</div></header>${blocks.length ? blocks.join('') : `<div class="empty-document"><h3>${t('empty')}</h3><p>${t('completeProfile')}</p></div>`}</div>`; }
  function docSection(title, content) { return `<section class="doc-section"><h3>${title}</h3>${content}</section>`; }
  function picker(kind, templates) { return `<div class="template-picker" role="group" aria-label="${t('template')}">${templates.map(name => `<button type="button" class="template-option ${profile[`${kind}Template`] === name ? 'is-selected' : ''}" data-template="${kind}" data-template-value="${name}">${t(name)}</button>`).join('')}</div>`; }
  function cvView() { return `<main id="main-content" class="app-main section-shell"><div class="view-heading"><div><div class="eyebrow">Pathly / ${t('cv')}</div><h1>${t('cvTitle')}</h1><p>${t('cvSubtitle')}</p></div><button class="button button-primary" data-action="print" type="button">${t('printPdf')}</button></div><div class="builder-layout"><section class="builder-tools"><p class="tool-label">${t('template')}</p>${picker('cv', ['modern', 'classic', 'focused'])}<p class="builder-note">${t('printHelp')}</p></section><section id="print-document" class="cv-paper template-${profile.cvTemplate}">${documentSections('cv')}</section></div></main>`; }

  function portfolioView() { return `<main id="main-content" class="app-main section-shell"><div class="view-heading"><div><div class="eyebrow">Pathly / ${t('portfolio')}</div><h1>${t('portfolioTitle')}</h1><p>${t('portfolioSubtitle')}</p></div><div class="action-stack"><button class="button button-primary" data-action="download-portfolio" type="button">${t('downloadPortfolio')}</button></div></div><div class="builder-tools portfolio-tools"><p class="tool-label">${t('template')}</p>${picker('portfolio', ['minimal', 'modern', 'creative', 'professional'])}</div><section class="portfolio-preview portfolio-${profile.portfolioTemplate}">${portfolioDocument()}</section><section class="share-card"><h2>${t('shareOnline')}</h2><p>${t('shareInfo')}</p></section></main>`; }
  function portfolioDocument() { const education = profile.education.length ? `<section><h3>${t('education')}</h3>${profile.education.map(x => `<p><strong>${esc([x.degree, x.major].filter(Boolean).join(' · '))}</strong><br>${esc(x.university || '')}</p>`).join('')}</section>` : '';
    const experience = profile.experience.length ? `<section><h3>${t('experience')}</h3>${profile.experience.map(x => `<article class="portfolio-entry"><h4>${esc(x.role || '')}</h4><p>${esc(x.company || '')}${dateRange(x) ? ` · ${dateRange(x)}` : ''}</p>${x.description ? `<p>${esc(x.description)}</p>` : ''}</article>`).join('')}</section>` : '';
    const projects = profile.projects.length ? `<section><h3>${t('projects')}</h3><div class="portfolio-projects">${profile.projects.map(x => `<article><h4>${esc(x.name || '')}</h4>${x.description ? `<p>${esc(x.description)}</p>` : ''}${x.tools ? `<small>${esc(x.tools)}</small>` : ''}${validUrl(x.link) ? `<a href="${esc(x.link)}" target="_blank" rel="noreferrer">${t('link')} ↗</a>` : ''}</article>`).join('')}</div></section>` : '';
    const certs = profile.certifications.length ? `<section><h3>${t('certifications')}</h3>${profile.certifications.map(x => `<p>${esc([x.name, x.issuer, formatDate(x.date)].filter(Boolean).join(' · '))}</p>`).join('')}</section>` : '';
    return `<div class="portfolio-inner"><header>${profile.photo ? `<img src="${profile.photo}" alt="">` : ''}<div class="doc-brand">Pathly / Portfolio</div><h2>${esc(profile.fullName || 'Your Name')}</h2>${profile.careerGoal ? `<p class="portfolio-goal">${esc(profile.careerGoal)}</p>` : ''}${profile.about ? `<p class="portfolio-intro">${esc(profile.about)}</p>` : ''}</header>${profile.skills.length ? `<section><h3>${t('skills')}</h3><p class="portfolio-skills">${profile.skills.map(esc).join(' · ')}</p></section>` : ''}${projects}${experience}${education}${certs}${profile.languages.length ? `<section><h3>${t('languages')}</h3><p>${profile.languages.map(esc).join(' · ')}</p></section>` : ''}<footer>${profile.email ? `<a href="mailto:${esc(profile.email)}">${esc(profile.email)}</a>` : ''}${validUrl(profile.linkedin) ? `<a href="${esc(profile.linkedin)}" target="_blank" rel="noreferrer">LinkedIn</a>` : ''}${validUrl(profile.github) ? `<a href="${esc(profile.github)}" target="_blank" rel="noreferrer">GitHub</a>` : ''}</footer></div>`; }

  function getGuidance() { const input = profile.careerGoal.toLowerCase().replace(/[^a-z0-9/ ]/g, '').trim(); const match = Object.entries(roles).find(([key]) => input.includes(key) || key.includes(input)); const current = profile.skills.map(s => s.toLowerCase().trim());
    if (!match) return { role: profile.careerGoal || t('targetCareer'), strengths: profile.skills.length ? profile.skills : [t('missing')], gaps: [t('roleFallback')], courses: [t('roleFallback')], projects: [t('roleFallback')], directions: [profile.careerGoal || t('roleFallback')], improvements: improvementList() };
    const [, spec] = match; const gaps = spec.skills.filter(skill => !current.some(value => value.includes(skill) || skill.includes(value)));
    const positives = []; if (profile.about) positives.push(t('about')); if (profile.education.length) positives.push(t('education')); if (profile.experience.length) positives.push(t('experience')); if (profile.projects.length) positives.push(t('projects')); positives.push(...profile.skills.slice(0, 3));
    return { role: spec.label[prefs.language], strengths: positives.length ? positives : [t('missing')], gaps: gaps.length ? gaps : [prefs.language === 'ar' ? 'لديك أساس جيد؛ ركّز على تعميق مشاريعك.' : 'You have a solid base; focus on deepening your projects.'], courses: spec.courses, projects: spec.projects, directions: [spec.label[prefs.language]], improvements: improvementList() };
  }
  function improvementList() { const list = []; if (!profile.about) list.push(t('tips')[0]); if (!profile.education.length && !profile.experience.length) list.push(t('tips')[1]); if (profile.skills.length < 3) list.push(t('tips')[2]); if (!profile.projects.length) list.push(t('tips')[3]); return list.length ? list : [prefs.language === 'ar' ? 'حافظ على تحديث أمثلة عملك مع تطورك.' : 'Keep your work examples current as you grow.']; }
  function advisorView() { const guide = getGuidance(); return `<main id="main-content" class="app-main section-shell"><div class="view-heading"><div><div class="eyebrow">Pathly / ${t('advisor')}</div><h1>${t('advisorTitle')}</h1><p>${t('advisorSubtitle')}</p></div><button class="button button-quiet" data-view="profile" type="button">${t('buildProfile')}</button></div><div class="journey-track"><span>${t('currentProfile')}</span><b>→</b><span>${t('gaps')}</span><b>→</b><span>${t('courses')}</span><b>→</b><span>${t('projects')}</span><b>→</b><span>${t('targetCareer')}</span><b>→</b><span>${t('careerGoal')}</span></div><div class="advisor-grid">${adviceCard(t('strengths'), guide.strengths)}${adviceCard(t('gaps'), guide.gaps)}${adviceCard(t('directions'), guide.directions)}${adviceCard(t('courses'), guide.courses)}${adviceCard(t('projectIdeas'), guide.projects)}${adviceCard(t('improvements'), guide.improvements)}</div><p class="rule-note">${t('ruleNote')}</p></main>`; }
  function adviceCard(title, items) { return `<article class="advice-card"><h2>${title}</h2><ul>${items.map(item => `<li>${esc(item)}</li>`).join('')}</ul></article>`; }

  function confirmDialog(message, action) { return `<dialog id="confirm-dialog"><form method="dialog" class="dialog-card"><p>${message}</p><div class="button-row"><button class="button button-secondary" value="cancel">${t('cancel')}</button><button class="button button-primary" value="confirm" data-confirm="${action}">${t('yes')}</button></div></form></dialog>`; }
  function render() { applyDocumentSettings(); let content = prefs.view === 'landing' ? landing() : `${header()}${prefs.view === 'dashboard' ? dashboard() : prefs.view === 'profile' ? profileView() : prefs.view === 'cv' ? cvView() : prefs.view === 'portfolio' ? portfolioView() : advisorView()}`; app.innerHTML = content; bind(); }

  function bind() {
    app.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => { prefs.view = button.dataset.view; savePrefs(); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }));
    app.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => action(button.dataset.action)));
    app.querySelectorAll('[data-template]').forEach(button => button.addEventListener('click', () => { profile[`${button.dataset.template}Template`] = button.dataset.templateValue; save(); render(); }));
    const profileForm = app.querySelector('#profile-form');
    if (profileForm) { profileForm.addEventListener('input', syncProfileForm); profileForm.querySelector('#photo-input')?.addEventListener('change', photoChange); }
    app.querySelectorAll('[data-add]').forEach(button => button.addEventListener('click', () => { const kind = button.dataset.add; profile[kind].push(kind === 'education' ? { university: '', major: '', degree: '', start: '', end: '', description: '' } : kind === 'experience' ? { role: '', company: '', start: '', end: '', description: '' } : kind === 'projects' ? { name: '', tools: '', link: '', description: '' } : { name: '', issuer: '', date: '', link: '' }); save(); render(); }));
    app.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => { profile[button.dataset.remove].splice(Number(button.dataset.index), 1); save(); render(); }));
    app.querySelectorAll('[data-remove-tag]').forEach(button => button.addEventListener('click', () => { profile[button.dataset.removeTag].splice(Number(button.dataset.index), 1); save(); render(); }));
    app.querySelectorAll('[data-tag-form]').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); const kind = form.dataset.tagForm; const value = new FormData(form).get('value').trim(); if (value && !profile[kind].some(v => v.toLowerCase() === value.toLowerCase())) { profile[kind].push(value); save(); render(); } }));
    app.querySelector('[data-form="goal"]')?.addEventListener('submit', event => { event.preventDefault(); profile.careerGoal = new FormData(event.currentTarget).get('careerGoal').trim(); save(); render(); });
  }
  function savePrefs() { try { localStorage.setItem(KEYS.prefs, JSON.stringify(prefs)); } catch { /* settings remain in session */ } }
  function syncProfileForm() { const form = app.querySelector('#profile-form'); ['fullName', 'email', 'about', 'linkedin', 'github', 'careerGoal'].forEach(name => { const field = form.elements[name]; if (field) profile[name] = field.value; }); form.querySelectorAll('[data-repeat]').forEach(card => { const kind = card.dataset.repeat; const index = Number(card.dataset.index); card.querySelectorAll('[name]').forEach(field => { profile[kind][index][field.name] = field.value; }); }); save(); }
  function action(name) { if (name === 'language') { prefs.language = prefs.language === 'en' ? 'ar' : 'en'; savePrefs(); render(); } else if (name === 'theme') { prefs.theme = prefs.theme === 'light' ? 'dark' : 'light'; savePrefs(); render(); } else if (name === 'print') { document.body.classList.add('printing-cv'); window.print(); setTimeout(() => document.body.classList.remove('printing-cv'), 500); } else if (name === 'download-portfolio') downloadPortfolio(); else if (name === 'remove-photo') { profile.photo = ''; save(); render(); } else if (name === 'example' || name === 'blank' || name === 'clear') { const dialogHolder = document.createElement('div'); dialogHolder.innerHTML = confirmDialog(name === 'example' ? t('confirmReplace') : t('confirmClear'), name); document.body.append(dialogHolder); const dialog = dialogHolder.querySelector('dialog'); dialog.addEventListener('close', () => { if (dialog.returnValue === 'confirm') { if (name === 'example') { profile = window.PathlyExampleData.create(); notify(t('exampleLoaded')); } else { profile = blankProfile(); notify(name === 'blank' ? t('blankStarted') : t('cleared')); } try { localStorage.setItem(KEYS.profile, JSON.stringify(profile)); } catch { notify(t('storageIssue')); } render(); } dialogHolder.remove(); }); dialog.querySelector('[data-confirm]')?.addEventListener('click', (event) => { event.preventDefault(); dialog.close('confirm'); }); dialog.showModal(); } }
  function photoChange(event) { const file = event.target.files?.[0]; if (!file || !file.type.startsWith('image/')) return; const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); const max = 240; const scale = Math.min(1, max / Math.max(image.width, image.height)); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); profile.photo = canvas.toDataURL('image/jpeg', 0.78); try { localStorage.setItem(KEYS.profile, JSON.stringify(profile)); render(); } catch { profile.photo = ''; notify(t('photoTooLarge')); render(); } }; image.src = reader.result; }; reader.readAsDataURL(file); }
  function downloadPortfolio() { const title = (profile.fullName || 'pathly-portfolio').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'pathly-portfolio'; const escapeHtml = value => String(value || '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch])); const data = JSON.stringify(profile).replace(/</g, '\\u003c'); const output = `<!doctype html><html lang="${prefs.language}" dir="${prefs.language === 'ar' ? 'rtl' : 'ltr'}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(profile.fullName || 'Portfolio')} — Pathly</title><style>body{margin:0;background:#f8f3e9;color:#2d211b;font:16px/1.65 system-ui,sans-serif}main{max-width:960px;margin:auto;padding:48px 20px}header{border-bottom:1px solid #ceb889;padding-bottom:24px}h1{font-size:clamp(2.3rem,7vw,5rem);margin:.2em 0}h2{margin-top:2rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.card{background:#fffdf8;border:1px solid #e5d8bd;padding:20px;border-radius:14px}a{color:#5a351e}</style><main id="root"></main><script>const p=${data};const e=${escapeHtml.toString()};const root=document.querySelector('#root');const section=(title,body)=>body?'<section><h2>'+title+'</h2>'+body+'</section>':'';root.innerHTML='<header><p>PATHLY / PORTFOLIO</p><h1>'+e(p.fullName||'Your Name')+'</h1><p>'+e(p.careerGoal||'')+'</p><p>'+e(p.about||'')+'</p></header>'+section('Skills',p.skills.length?'<p>'+p.skills.map(e).join(' · ')+'</p>':'')+section('Projects',p.projects.length?'<div class="grid">'+p.projects.map(x=>'<article class="card"><h3>'+e(x.name)+'</h3><p>'+e(x.description)+'</p><small>'+e(x.tools)+'</small></article>').join('')+'</div>':'')+section('Experience',p.experience.length?p.experience.map(x=>'<article><h3>'+e(x.role)+' · '+e(x.company)+'</h3><p>'+e(x.description)+'</p></article>').join(''):'')+section('Education',p.education.length?p.education.map(x=>'<p><strong>'+e(x.degree)+' · '+e(x.major)+'</strong><br>'+e(x.university)+'</p>').join(''):'')+section('Certifications',p.certifications.length?p.certifications.map(x=>'<p>'+e(x.name)+' · '+e(x.issuer)+'</p>').join(''):'')+'<footer><p>'+e(p.email)+'</p></footer>';<\/script>`; const blob = new Blob([output], { type: 'text/html;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${title}.html`; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }

  if (profileSeeded) { try { localStorage.setItem(KEYS.profile, JSON.stringify(profile)); } catch { /* The app remains usable for this browser session. */ } }
  render();
})();
